tasks:
  - init: |
      echo 'TODO: build project'
      python -m pip install --upgrade pip
      python -m pip install --upgrade pip setuptools wheel pip-tools robotframework
      python -m pip install --upgrade git+https://github.com/my8100/scrapydweb.git 
      sudo apt-get install lynx direnv -y
    command: |
      echo 'TODO: start app'
      python -m pip install -U -r requirements.txt
      # printf "#!/usr/bin/env bash \nexport z='EasyQuest'" > .envrc;direnv allow
      echo 'TODO:Good!!!'

vscode:
  extensions:
    - ms-python.python
    - ms-toolsai.jupyter
    - d-biehl.robotcode
    - magicstack.magicpython
    - formulahendry.code-runner
